sudo: required

language: go

services:
  - docker

os:
  - linux

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

install:
  - go get github.com/gobwas/pool
  - go get github.com/gobwas/httphead

script:
  - make test
  - make autobahn 
