sudo: required

language: go

services:
  - docker

os:
  - linux
  - windows

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x

install:
  - go get github.com/gobwas/pool
  - go get github.com/gobwas/httphead

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then go test ./...; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make test autobahn; fi
